/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author Arfan
 */
public class FormDaftar extends javax.swing.JFrame {

    /**
     * Creates new form FormDaftar
     */
    public FormDaftar() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void login() {
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        tnohp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_daftar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 84, 65));
        jLabel4.setText("Daftar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(880, 240, 170, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 84, 64));
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 350, 70, 50);

        tnama.setBackground(new java.awt.Color(228, 243, 220));
        tnama.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tnama.setForeground(new java.awt.Color(27, 84, 64));
        tnama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(tnama);
        tnama.setBounds(720, 410, 470, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 84, 64));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 480, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 84, 64));
        jLabel7.setText("No Hp");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(780, 600, 80, 50);

        tpass.setBackground(new java.awt.Color(229, 244, 221));
        tpass.setAutoscrolls(false);
        tpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(tpass);
        tpass.setBounds(720, 790, 470, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1210, 190, 40, 60);

        tnohp.setBackground(new java.awt.Color(228, 243, 220));
        tnohp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tnohp.setForeground(new java.awt.Color(27, 84, 64));
        tnohp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(tnohp);
        tnohp.setBounds(720, 660, 470, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 84, 64));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(780, 740, 110, 31);

        btn_daftar.setBackground(new java.awt.Color(205, 226, 200));
        btn_daftar.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        btn_daftar.setForeground(new java.awt.Color(27, 84, 64));
        btn_daftar.setText("Daftar");
        btn_daftar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        btn_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_daftar.setFocusable(false);
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar);
        btn_daftar.setBounds(720, 910, 470, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 340, 50, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(720, 480, 50, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(720, 600, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 730, 50, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(690, 20, 510, 140);

        temail.setBackground(new java.awt.Color(228, 243, 220));
        temail.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        temail.setForeground(new java.awt.Color(27, 84, 64));
        temail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(temail);
        temail.setBounds(720, 530, 470, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 190, 590, 830);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1940, 1100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO data_guru (username, email, no_hp, password) VALUES (?, ?, ?, ?)";
            Connection conn = koneksi.koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tnama.getText());
            pst.setString(2, temail.getText());
            pst.setString(3, tnohp.getText());
            pst.setString(4, tpass.getText());
            
            pst.executeUpdate();
            login();
            
        } catch (SQLException e) {
            System.out.println("Gagal simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDaftar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnohp;
    private javax.swing.JPasswordField tpass;
    // End of variables declaration//GEN-END:variables
}
