/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Window;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Arfan
 */
public class FormDataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form FormDataSiswa
     */
    public FormDataSiswa() {
        initComponents();
        jTextFieldID.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Mengakses header JTable
        JTableHeader header = tabelSiswa.getTableHeader();

        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                label.setBackground(Color.BLACK); 
                label.setForeground(Color.WHITE);
                label.setOpaque(true); 
                label.setFont(new Font("Segoe UI", Font.BOLD, 20));
                label.setHorizontalAlignment(SwingConstants.CENTER); 

                label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, Color.WHITE));
                return label;
            }
        });
        tampilData();
    }
    
    
    
    private void cariData(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Umur");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Kelas");

        try {
            String sql = "SELECT * FROM data_siswa WHERE nama LIKE ?";
            Connection conn = koneksi.koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getString("nama"),
                    rs.getInt("umur"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("kelas")
                });
            }

            tabelSiswa.setModel(model);

        } catch (SQLException e) {
            System.out.println("Gagal cari data: " + e.getMessage());
        }
    }

    
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");  // Kolom ID ditambahkan pertama
        model.addColumn("Nama");
        model.addColumn("Umur");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Kelas");

        try {
            String sql = "SELECT * FROM data_siswa";
            Connection conn = koneksi.koneksi.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_murid"),
                    rs.getString("nama"),
                    rs.getInt("umur"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("kelas")
                });
            }

            tabelSiswa.setModel(model);

            // Sembunyikan kolom ID (kolom ke-0)
            tabelSiswa.getColumnModel().getColumn(0).setMinWidth(0);
            tabelSiswa.getColumnModel().getColumn(0).setMaxWidth(0);
            tabelSiswa.getColumnModel().getColumn(0).setWidth(0);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }


    private void resetForm() {
        jTextFieldNama.setText("");
        jTextFieldUmur.setText("");
        jTextFieldJK.setText("");
        jTextFieldKelas.setText("");
        jTextFieldID.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSiswa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldUmur = new javax.swing.JTextField();
        jTextFieldKelas = new javax.swing.JTextField();
        jTextFieldJK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 84, 64));
        jLabel2.setText("Form Data Siswa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 30, 520, 100);

        jButton1.setBackground(new java.awt.Color(205, 226, 200));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(27, 84, 64));
        jButton1.setText("Save");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 810, 180, 70);

        jButton2.setBackground(new java.awt.Color(205, 226, 200));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(27, 84, 64));
        jButton2.setText("Edit");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 810, 180, 70);

        jButton3.setBackground(new java.awt.Color(205, 226, 200));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton3.setForeground(new java.awt.Color(27, 84, 64));
        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 810, 180, 70);

        tabelSiswa.setBackground(new java.awt.Color(205, 226, 200));
        tabelSiswa.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tabelSiswa.setForeground(new java.awt.Color(27, 84, 64));
        tabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Umur", "Jenis Kelamin", "Kelas"
            }
        ));
        tabelSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelSiswa.setGridColor(new java.awt.Color(25, 85, 60));
        tabelSiswa.setRowHeight(50);
        tabelSiswa.setSelectionBackground(new java.awt.Color(228, 243, 220));
        tabelSiswa.setSelectionForeground(new java.awt.Color(27, 84, 64));
        tabelSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSiswa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(940, 300, 920, 740);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 84, 64));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 240, 70, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 84, 64));
        jLabel5.setText("Umur");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 380, 70, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 84, 64));
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 500, 170, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 84, 64));
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 630, 70, 50);

        jButton4.setBackground(new java.awt.Color(205, 226, 200));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton4.setForeground(new java.awt.Color(27, 84, 64));
        jButton4.setText("Kembali");
        jButton4.setToolTipText("");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 950, 750, 80);

        jTextFieldNama.setBackground(new java.awt.Color(228, 243, 220));
        jTextFieldNama.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextFieldNama.setForeground(new java.awt.Color(27, 84, 64));
        jTextFieldNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(140, 300, 630, 60);

        jTextFieldUmur.setBackground(new java.awt.Color(228, 243, 220));
        jTextFieldUmur.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextFieldUmur.setForeground(new java.awt.Color(27, 84, 64));
        jTextFieldUmur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(jTextFieldUmur);
        jTextFieldUmur.setBounds(140, 430, 630, 60);

        jTextFieldKelas.setBackground(new java.awt.Color(228, 243, 220));
        jTextFieldKelas.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextFieldKelas.setForeground(new java.awt.Color(27, 84, 64));
        jTextFieldKelas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(jTextFieldKelas);
        jTextFieldKelas.setBounds(140, 690, 630, 60);

        jTextFieldJK.setBackground(new java.awt.Color(228, 243, 220));
        jTextFieldJK.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextFieldJK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        getContentPane().add(jTextFieldJK);
        jTextFieldJK.setBounds(140, 560, 630, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 240, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/13.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 500, 60, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/12.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 620, 70, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/11.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 360, 60, 70);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 84, 64));
        jLabel12.setText("Cari Data Siswa");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1050, 220, 180, 30);

        jTextFieldCari.setBackground(new java.awt.Color(228, 243, 220));
        jTextFieldCari.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jTextFieldCari.setForeground(new java.awt.Color(27, 84, 64));
        jTextFieldCari.setToolTipText("");
        jTextFieldCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 3, true));
        jTextFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCariActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCari);
        jTextFieldCari.setBounds(1240, 200, 400, 60);

        jButton5.setBackground(new java.awt.Color(205, 226, 200));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton5.setForeground(new java.awt.Color(27, 84, 64));
        jButton5.setText("Cari");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1660, 200, 180, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 170, 750, 770);

        jTextFieldID.setText("jTextField1");
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(420, 190, 63, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/19.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(970, 200, 60, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 85, 60), 2, true));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(940, 170, 920, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1950, 1099);

        setSize(new java.awt.Dimension(1947, 1091));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            String sql = "INSERT INTO data_siswa (nama, umur, jenis_kelamin, kelas) VALUES (?, ?, ?, ?)";
            Connection conn = koneksi.koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, jTextFieldNama.getText());
            pst.setInt(2, Integer.parseInt(jTextFieldUmur.getText()));
            pst.setString(3, jTextFieldJK.getText());
            pst.setString(4, jTextFieldKelas.getText());
            
            pst.executeUpdate();
            tampilData();
            resetForm();
            
        } catch (SQLException e) {
            System.out.println("Gagal simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            int id = Integer.parseInt(jTextFieldID.getText()); 

            String sql = "UPDATE data_siswa SET nama=?, umur=?, jenis_kelamin=?, kelas=? WHERE id_murid=?";
            Connection conn = koneksi.koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, jTextFieldNama.getText());
            pst.setInt(2, Integer.parseInt(jTextFieldUmur.getText()));
            pst.setString(3, jTextFieldJK.getText());
            pst.setString(4, jTextFieldKelas.getText());
            pst.setInt(5, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
            tampilData();
            resetForm();

        } catch (SQLException e) {
            System.out.println("Gagal update: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            int id = Integer.parseInt(jTextFieldID.getText());

            int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM data_siswa WHERE id_murid=?";
                Connection conn = koneksi.koneksi.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, id);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                tampilData();
                resetForm();
            }

        } catch (SQLException e) {
            System.out.println("Gagal hapus: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void tabelSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSiswaMouseClicked
        int baris = tabelSiswa.getSelectedRow();
        jTextFieldID.setText(tabelSiswa.getValueAt(baris, 0).toString()); 
        jTextFieldNama.setText(tabelSiswa.getValueAt(baris, 1).toString());
        jTextFieldUmur.setText(tabelSiswa.getValueAt(baris, 2).toString());
        jTextFieldJK.setText(tabelSiswa.getValueAt(baris, 3).toString());
        jTextFieldKelas.setText(tabelSiswa.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tabelSiswaMouseClicked

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String keyword = jTextFieldCari.getText();
        cariData(keyword);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldJK;
    private javax.swing.JTextField jTextFieldKelas;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldUmur;
    private javax.swing.JTable tabelSiswa;
    // End of variables declaration//GEN-END:variables
}
