/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JFrame;

/**
 *
 * @author Arfan
 */
public class FormCatatanSiswa extends javax.swing.JFrame {

    /**
     * Creates new form FormDataSiswa
     */
    public FormCatatanSiswa() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 84, 64));
        jLabel2.setText("Form Catatan Perkembangan Siswa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 30, 1080, 100);

        jButton1.setBackground(new java.awt.Color(205, 226, 200));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(27, 84, 64));
        jButton1.setText("Save");
        jButton1.setBorder(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 800, 180, 70);

        jButton2.setBackground(new java.awt.Color(205, 226, 200));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(27, 84, 64));
        jButton2.setText("Edit");
        jButton2.setBorder(null);
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 800, 190, 70);

        jButton3.setBackground(new java.awt.Color(205, 226, 200));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton3.setForeground(new java.awt.Color(27, 84, 64));
        jButton3.setText("Delete");
        jButton3.setBorder(null);
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 800, 180, 70);

        jTable1.setBackground(new java.awt.Color(205, 226, 200));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTable1.setForeground(new java.awt.Color(27, 84, 64));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Hafalan", "Hadits", "Akhlak"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(27, 84, 64));
        jTable1.setSelectionBackground(new java.awt.Color(228, 243, 220));
        jTable1.setSelectionForeground(new java.awt.Color(27, 84, 64));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(910, 180, 920, 740);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 84, 64));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 230, 70, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 84, 64));
        jLabel5.setText("Hafalan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 370, 90, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 84, 64));
        jLabel6.setText("Hadits");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 500, 80, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 84, 64));
        jLabel7.setText("Akhlak");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 630, 80, 50);

        jButton4.setBackground(new java.awt.Color(205, 226, 200));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton4.setForeground(new java.awt.Color(27, 84, 64));
        jButton4.setText("Kembali");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 970, 320, 80);

        jTextField1.setBackground(new java.awt.Color(228, 243, 220));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(27, 84, 64));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 300, 630, 60);

        jTextField2.setBackground(new java.awt.Color(228, 243, 220));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(27, 84, 64));
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 430, 630, 60);

        jTextField4.setBackground(new java.awt.Color(228, 243, 220));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(27, 84, 64));
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 690, 630, 60);

        jTextField3.setBackground(new java.awt.Color(228, 243, 220));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 560, 630, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 240, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/18.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 500, 60, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/17.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 620, 70, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 360, 60, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 180, 750, 740);

        jButton5.setBackground(new java.awt.Color(205, 226, 200));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton5.setForeground(new java.awt.Color(27, 84, 64));
        jButton5.setText("Cetak PDF");
        getContentPane().add(jButton5);
        jButton5.setBounds(540, 970, 330, 80);

        jButton6.setBackground(new java.awt.Color(205, 226, 200));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton6.setForeground(new java.awt.Color(27, 84, 64));
        jButton6.setText("Cetak Word");
        getContentPane().add(jButton6);
        jButton6.setBounds(990, 970, 350, 80);

        jButton7.setBackground(new java.awt.Color(205, 226, 200));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jButton7.setForeground(new java.awt.Color(27, 84, 64));
        jButton7.setText("Cetak Excel");
        getContentPane().add(jButton7);
        jButton7.setBounds(1490, 970, 340, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1950, 1099);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCatatanSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCatatanSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCatatanSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCatatanSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCatatanSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
